---
title: 回归分析作业
author: ''
date: '2022-03-28'
slug: ''
categories: []
tags: []
description: 大二下学期.教材《应用回归分析》（第五版）
---

# 一
## 习题2.14
```{r}
# 回归模型的拟合
t2.14 <- data.frame(
  月份 = c(1, 2, 3, 4, 5),
  x = c(1, 2, 3, 4, 5),
  y = c(10, 10, 20, 20, 40)
)
model <- lm(y ~ x,
            data=t2.14)
```

### 散点图

```{r}
# 绘制拟合图
attach(t2.14)
model <- lm(y ~ x)
plot(y ~ x)
text(y ~ x, label=月份, cex=0.6, adj=c(-0.6,0.25), col=4)
abline(model, col=2,lwd=2)
n = nrow(t2.14)
for(i in 1:n){
    segments(t2.14[i,2], t2.14[i,3], t2.14[i,2], model$fitted[i])
}
```

### 汇总

```{r}
summary(model)
```

### 置信区间

```{r}
#计算回归系数的置信区间
confint(model,level=0.95)
```

### 方差分析

```{r}
# 输出方差分析表
anova(model)
```

### 相关系数的显著性检验

```{r}
cor.test(x, y, method='pearson')
```

### 残差图

```{r}
# 绘制残差图
plot(model, which=1)
```

### 广告费用4.2万元时

```{r}
predict.lm(model,
           newdata=data.frame(x=4.2),
           interval='confidence',
           level=0.95)
```

## 习题2.15
```{r}
t2.15 <- data.frame(
  周序号 = 1:10,
  x = c(825, 215, 1070, 550, 480, 920, 1350, 325, 670, 1215),
  y = c(3.5, 1.0, 4.0, 2.0, 1.0, 3.0, 4.5, 1.5, 3.0, 5.0)
)
model <- lm(y ~ x,
            data=t2.15)# 拟合模型
summary(model)# 输出结果
confint(model,level=0.95)# 输出置信区间
anova(model)# 输出方差分析表
```

```{r}
# 绘制拟合图
attach(t2.15)
model <- lm(y ~ x)
plot(y ~ x)
text(y ~ x, label=周序号, cex=0.6, adj=c(-0.6,0.25), col=4)
abline(model, col=2,lwd=2)
n = nrow(t2.14)
for(i in 1:n){
    segments(t2.14[i,2], t2.14[i,3], t2.14[i,2], model$fitted[i])
}
```

# text
```{r}
library(haven)
li2_2 <- read_sav("C:/Users/Gleko/Desktop/作业/应用回归分析/应用回归分析数据（第5版）/例题SPSS格式/li2.2.sav")
# 回归模型的拟合
t2.14 <- li2_2
model <- lm(y ~ x,
            data=t2.14)
summary(model)
#计算回归系数的置信区间
confint(model,level=0.95)
# 输出方差分析表
anova(model)

# 绘制拟合图
attach(t2.14)
model <- lm(y ~ x)
plot(y ~ x)
text(y ~ x, label=年份, cex=0.6, adj=c(-0.6,0.25), col=4)
abline(model, col=2,lwd=2)
n = nrow(t2.14)
```