project:
  type: website
  
website: 
  title: "Stulink"
  navbar: 
    title: " "
    background: white
    foreground: black
format:
  html:
    theme: 
      - journal
      - custom.scss
    css: styles.css
    fontsize: 1.1em
    smooth-scroll: true
    toc: true
listing: 
  filter-ui: false
  fields: [date, author, title, description]
  