project:
  type: website
  
website:
  title: "Stulink"
  site-url: https://stulink.netlify.app/
  description: "Blogs of Stulink"
  navbar:
    right:
      - about.qmd
format:
  html:
    theme:
      - Litera
      - custom.scss
    css: styles.css
    fontsize: 1.1em
    smooth-scroll: true
    toc: true
    toc-depth: 4