project:
  type: website
  
website:
  title: "Stulink"
  site-url: https://stulink.netlify.app/
  description: "Blogs of Stulink"
  navbar:
    background: light
    right:
      - about.qmd
format:
  html:
    theme:
      - cosmo
      - custom.scss
    css: styles.css
    fontsize: 1.05em
    smooth-scroll: true
    toc: true
    toc-depth: 4