project:
  type: website

website:
  title: "Stulink"
  site-url: https://stulink.netlify.app/
  description: "Blogs of Stulink"
  navbar:
    background: light
    right:
      - about.qmd
      - icon: github
        href: https://github.com/GlekoMa
  body-footer: waline.html
  margin-header: subscribe.html
format:
  html:
    theme: cosmo
    css: styles.css



