{
  "hash": "8e39612900deb7d694a2070de201cd69",
  "result": {
    "markdown": "---\ntitle: 习题4.9\nfig-height: 3\nfig-width: 5\ndescription: 违背基本假设的情况\n---\n\n> **下表是用电高峰每小时用电量$y$与每月总用电量$x$的数据。**\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(haven)\ndata = read_sav(\"data/xt4.9.sav\")\nhead(data)\n```\n\n::: {.cell-output-stdout}\n```\n# A tibble: 6 × 3\n   序号     x     y\n  <dbl> <dbl> <dbl>\n1     1   679  0.79\n2     2   292  0.44\n3     3  1012  0.56\n4     4   493  0.79\n5     5   582  2.7 \n6     6  1156  3.64\n```\n:::\n:::\n\n#### 1. 用普通最小二乘法建立$y$与$x$的回归方程，并画出残差散点图\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel0 = lm(y ~ x, data)\nmodel0\n```\n\n::: {.cell-output-stdout}\n```\n\nCall:\nlm(formula = y ~ x, data = data)\n\nCoefficients:\n(Intercept)            x  \n  -0.831304     0.003683  \n```\n:::\n:::\n\n答：回归方程为：$\\hat{y} = -0.8313 + 0.0037x$。\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\nggplot(model0, aes(x=x, y=.resid)) + \n    geom_point() + \n    geom_hline(yintercept = 0) + \n    labs(y=\"Residuals\")\n```\n\n::: {.cell-output-display}\n![](xt4.9_files/figure-html/unnamed-chunk-3-1.png){width=480}\n:::\n:::\n\n#### 2. 诊断该问题是否存在异方差性\n\n::: {.cell}\n\n```{.r .cell-code}\n# 等级相关系数法（Spearman检验）\ncor.test(data$x, \n         abs(resid(model0)), \n         alternative='two.sided',\n         method=\"spearman\", \n         conf.level=0.95)\n```\n\n::: {.cell-output-stdout}\n```\n\n\tSpearman's rank correlation rho\n\ndata:  data$x and abs(resid(model0))\nS = 16928, p-value = 0.02091\nalternative hypothesis: true rho is not equal to 0\nsample estimates:\n      rho \n0.3175294 \n```\n:::\n:::\n\n答：$|e_i|$与$x_i$的等级相关系数=0.318，P值=0.021，存在异方差性。\n\n#### 3. 如果存在异方差性，用幂指数型的权函数建立加权最小二乘回归方程\n\n::: {.cell}\n\n```{.r .cell-code}\n# 编写寻找最优权函数\n# 特定于幂指型权函数的一元回归\nbest_weight_1d = function(data, left=-2, right=2){\n    the_seq = seq(left, right, 0.5)\n    vec = rep(NA, length(the_seq))\n    j = 1\n    for (m in the_seq){\n        model1 = lm(y ~ x,\n                    weights=1/x^m,\n                    data=data)\n        vec[j] = logLik(model1) # logLik函数计算模型的对数似然值\n        j = j + 1\n    }\n    best_local = which.max(vec)\n    if(best_local != left & best_local != right){\n        cat(\"幂指数最优取值为:\", the_seq[best_local])\n    }else if(best_local == left){\n        cat(\"最优值在边界达到，请扩充范围（left）\")\n    }else{\n        cat(\"最优值在边界达到，请扩充范围（right）\")\n    }\n}\nbest_weight_1d(data)\n```\n\n::: {.cell-output-stdout}\n```\n幂指数最优取值为: 1.5\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# 令m=1.5\nmodel1 = lm(y ~ x, weights=1/x^1.5, data=data)\nmodel1\n```\n\n::: {.cell-output-stdout}\n```\n\nCall:\nlm(formula = y ~ x, data = data, weights = 1/x^1.5)\n\nCoefficients:\n(Intercept)            x  \n  -0.683463     0.003557  \n```\n:::\n:::\n\n答：加权最小二乘回归方程为：$\\hat{y} = -0.683 + 0.00356x$。等级相关系数为-0.076，P值为0.591，异方差性已消除。因$R^2=0.659$，小于普通最小二乘的0.705，说明加权最小二乘的效果不好。\n\n#### 4. 用方差稳定变换$y'=\\sqrt{y}$消除异方差性\n\n::: {.cell}\n\n```{.r .cell-code}\ndata$y = sqrt(data$y)\nmodel2 = lm(y ~ x, data)\nmodel2\n```\n\n::: {.cell-output-stdout}\n```\n\nCall:\nlm(formula = y ~ x, data = data)\n\nCoefficients:\n(Intercept)            x  \n  0.5822259    0.0009529  \n```\n:::\n:::\n\n答：经过方差稳定性变换后的回归方程为：$\\hat{y}^{'} = 0.5822 + 0.0009529x$。等级相关系数为0.160，P值为0.254，异方差性已消除。因$R^2=0.710$，优于普通最小二乘的效果。",
    "supporting": [
      "xt4.9_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": [],
    "engineDependencies": {},
    "preserve": {},
    "postProcess": null
  }
}