{
  "hash": "88599475d13ba0f5ecf5c06b20ffb1f0",
  "result": {
    "markdown": "---\ntitle: \"探索性数据分析 | 1st\"\nauthor: \"Gleko Ma\"\ndate: \"2022/4/22\"\ncategories: [code, analysis]\nimage: \"hello.jpg\"\nknitr: true\n---\n\nFor school work.\n\n## 示例模型的重演\n\n##### 建立数据框\n\n::: {.cell}\n\n```{.r .cell-code}\noptions(digits = 3)\ndf0 = data.frame(\n    '人均专著' = c(0.1, 0.2, 0.4, 0.9, 1.2),\n    '生师比' = c(5, 6, 7, 10, 2),\n    '科研经费' = c(5000, 6000, 7000, 10000, 400),\n    '逾期毕业率' = c(4.7, 5.6, 6.7, 2.3, 1.8)\n) # df0作为备份\ndf = df0\nknitr::kable(df)\n```\n\n::: {.cell-output-display}\n| 人均专著| 生师比| 科研经费| 逾期毕业率|\n|--------:|------:|--------:|----------:|\n|      0.1|      5|     5000|        4.7|\n|      0.2|      6|     6000|        5.6|\n|      0.4|      7|     7000|        6.7|\n|      0.9|     10|    10000|        2.3|\n|      1.2|      2|      400|        1.8|\n:::\n:::\n\n##### 区间型属性变换\n\n变换公式：\n$$\nb_{i j}=\\left\\{\\begin{array}{ll}\n1-\\left(a_{j}^{0}-a_{i j}\\right) /\\left(a_{j}^{0}-a_{j}^{\\prime}\\right), & a_{j}^{\\prime} \\leq a_{i j}<a_{j}^{0} \\\\\n1, & a_{j}^{0} \\leq a_{i j}<a_{j}^{*} \\\\\n1-\\left(a_{i j}-a_{j}^{*}\\right) /\\left(a_{j}^{\\prime \\prime}-a_{j}^{*}\\right), & a_{j}^{*} \\leq a_{i j}<a_{j}^{\\prime \\prime} \\\\\n0, & \\text { 其他 }\n\\end{array}\\right.\n$$\n\n::: {.cell}\n\n```{.r .cell-code}\ndf$生师比 = c(1, 1, 0.8333, 0.8333, 0)\nknitr::kable(df)\n```\n\n::: {.cell-output-display}\n| 人均专著| 生师比| 科研经费| 逾期毕业率|\n|--------:|------:|--------:|----------:|\n|      0.1|  1.000|     5000|        4.7|\n|      0.2|  1.000|     6000|        5.6|\n|      0.4|  0.833|     7000|        6.7|\n|      0.9|  0.833|    10000|        2.3|\n|      1.2|  0.000|      400|        1.8|\n:::\n:::\n\n##### 数据标准化\n\n::: {.cell}\n\n```{.r .cell-code}\nmom = function(col){sqrt(sum(col^2))}\nfor (i in 1:4){df[, i] = df[, i]/mom(df[, i])}\nknitr::kable(df)\n```\n\n::: {.cell-output-display}\n| 人均专著| 生师比| 科研经费| 逾期毕业率|\n|--------:|------:|--------:|----------:|\n|    0.064|  0.543|    0.345|      0.455|\n|    0.128|  0.543|    0.414|      0.542|\n|    0.255|  0.453|    0.483|      0.648|\n|    0.574|  0.453|    0.690|      0.222|\n|    0.765|  0.000|    0.028|      0.174|\n:::\n:::\n\n##### 数据加权\n\n::: {.cell}\n\n```{.r .cell-code}\nw = c(0.2, 0.3, 0.4, 0.1)\nfor (i in 1:4){df[, i] = w[i]*df[, i]}\nknitr::kable(df)\n```\n\n::: {.cell-output-display}\n| 人均专著| 生师比| 科研经费| 逾期毕业率|\n|--------:|------:|--------:|----------:|\n|    0.013|  0.163|    0.138|      0.045|\n|    0.026|  0.163|    0.166|      0.054|\n|    0.051|  0.136|    0.193|      0.065|\n|    0.115|  0.136|    0.276|      0.022|\n|    0.153|  0.000|    0.011|      0.017|\n:::\n:::\n\n##### 到正负理想解的距离\n\n::: {.cell}\n\n```{.r .cell-code}\ngood = c(0.1530, 0.163, 0.276, 0.0648)\nbad = c(0.0128, 0.000, 0.011, 0.0174)\ngood_d = function(row){sqrt(sum((row - good)^2))}\nbad_d = function(row){sqrt(sum((row - bad)^2))}\ndf_over = data.frame(\n    s = rep(NA, 5),\n    s0 = rep(NA, 5)\n)\nfor (i in 1:5){\n    df_over$s[i] = good_d(df[i, ])\n    df_over$s0[i] = bad_d(df[i, ])\n}\nknitr::kable(df_over)\n```\n\n::: {.cell-output-display}\n|     s|    s0|\n|-----:|-----:|\n| 0.198| 0.208|\n| 0.169| 0.228|\n| 0.134| 0.235|\n| 0.063| 0.315|\n| 0.315| 0.140|\n:::\n:::\n\n##### 计算综合指标值\n\n::: {.cell}\n\n```{.r .cell-code}\ndf_over$f = df_over$s0/(df_over$s + df_over$s0)\nknitr::kable(df_over)\n```\n\n::: {.cell-output-display}\n|     s|    s0|     f|\n|-----:|-----:|-----:|\n| 0.198| 0.208| 0.513|\n| 0.169| 0.228| 0.574|\n| 0.134| 0.235| 0.637|\n| 0.063| 0.315| 0.832|\n| 0.315| 0.140| 0.308|\n:::\n:::\n\n故结论为：4 > 3 > 2 > 1 > 5\n\n## 探索性分析\n\n##### 检查变量相关性\n\n对数据中各属性间的相关性进行可视化。\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(GGally)\nggpairs(df0)\n```\n\n::: {.cell-output-display}\n![](EDA_1_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n**生师比**与**科研经费**的相关系数高达0.991。\n\n既然生师比与科研经费相关性这么高，那么现在计算一下人均科研经费：\n\n::: {.cell}\n\n```{.r .cell-code}\ndf_avg = data.frame(\n    '人均经费' = df0$科研经费/df0$生师比\n) |> t()\nknitr::kable(df_avg)\n```\n\n::: {.cell-output-display}\n|         |     |     |     |     |    |\n|:--------|----:|----:|----:|----:|---:|\n|人均经费 | 1000| 1000| 1000| 1000| 200|\n:::\n:::\n\n可以清楚明白准确无误地看出来，第5行数据是个\"异类\"。\n\n让我们再回头仔细观察一下它们：\n\n::: {.cell}\n\n```{.r .cell-code}\nknitr::kable(df0)\n```\n\n::: {.cell-output-display}\n| 人均专著| 生师比| 科研经费| 逾期毕业率|\n|--------:|------:|--------:|----------:|\n|      0.1|      5|     5000|        4.7|\n|      0.2|      6|     6000|        5.6|\n|      0.4|      7|     7000|        6.7|\n|      0.9|     10|    10000|        2.3|\n|      1.2|      2|      400|        1.8|\n:::\n:::\n\n第五个学校虽然科研经费少，但生师比、人均专著与逾期毕业率都很理想，可以猜测此学校类型为弱工科院校，亦或者某类新型院校。数据如此理想的院校，相见恨晚，本文私自将其内定为第一名，并将其在后续分析中剔除。\n\n##### 消除高度相关的列\n\n既剔除了第五个院校，那么剩下四个院校的生师比与科研经费就完美符合$\\hat{y}=1000\\hat{x}$.的等式了，如此可将科研经费列剔除[^1]。\n\n[^1]: 为啥可剔除？因为只取样本的充分统计量即可哇\n\n于是现在剩余数据如下：\n\n::: {.cell}\n\n```{.r .cell-code}\ndf0 = df0[-5, -3]\nknitr::kable(df0)\n```\n\n::: {.cell-output-display}\n| 人均专著| 生师比| 逾期毕业率|\n|--------:|------:|----------:|\n|      0.1|      5|        4.7|\n|      0.2|      6|        5.6|\n|      0.4|      7|        6.7|\n|      0.9|     10|        2.3|\n:::\n:::\n\n再对其相关性进行可视化\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(GGally)\nggpairs(df0)\n```\n\n::: {.cell-output-display}\n![](EDA_1_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n这下生师比与人均专著又展现出了极高的相关性。那么现在对这两个变量进行可视化与回归拟合：\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\nggplot(df0, aes(x=`生师比`, y=`人均专著`)) + \n    geom_point(aes(x=`生师比`, y=`人均专著`)) + \n    geom_smooth(method = \"lm\")\n```\n\n::: {.cell-output-display}\n![](EDA_1_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n\n```{.r .cell-code}\nmodel1 = lm(`人均专著` ~ `生师比`, data = df0)\nkb1 = summary(model1)[4]$coefficients\ncolnames(kb1) = c('估计值', '标准误', 't值', 'P值')\nrownames(kb1) = c('截距', '生师比')\nknitr::kable(kb1)\n```\n\n::: {.cell-output-display}\n|       | 估计值| 标准误|   t值|   P值|\n|:------|------:|------:|-----:|-----:|\n|截距   | -0.750|  0.063| -11.8| 0.007|\n|生师比 |  0.164|  0.009|  18.8| 0.003|\n:::\n:::\n\n的确，拟合的很好。回归方程：$\\hat{y} =0.164\\hat{x}-0.750$.\n\n如此，我们又可以剔除一列：人均专著。\n\n::: {.cell}\n\n```{.r .cell-code}\ndf0 = df0[, -1]\n```\n:::\n\n现在只剩下孤零零的两列四行数据了：\n\n::: {.cell}\n\n```{.r .cell-code}\nknitr::kable(df0)\n```\n\n::: {.cell-output-display}\n| 生师比| 逾期毕业率|\n|------:|----------:|\n|      5|        4.7|\n|      6|        5.6|\n|      7|        6.7|\n|     10|        2.3|\n:::\n:::\n\n接下来该怎么办？明天再想，收工！",
    "supporting": [
      "EDA_1_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": [],
    "engineDependencies": {},
    "preserve": {},
    "postProcess": null
  }
}