---
title: 习题3.11
fig-height: 3
fig-width: 5
description: 多元线性回归
---

> **题目：研究货运总量$y$（万吨）与工业总产值$x_1$（亿元）、农业总产值$x_2$（亿元）、居民非商品支出$x_3$（亿元）的关系。数据如下表所示。**

```{r}
# 课本数据有10行，数据集不知何故多出一行
library(haven)
data = read_sav("data/xt3.11.sav")[-11, ]
head(data)
```

#### 1. 计算出$y$，$x_1$，$x_2$，$x_3$的相关系数矩阵。

```{r}
cor(data)
```

#### 2. 求$y$关于$x_1$，$x_2$，$x_3$的三元线性方程

```{r}
model0 = lm(Y ~ X1 + X2 + X3, data)
model0
```

#### 3. 对所求得的方程做拟合优度检验

```{r}
Sm0 = summary(model0)
Sm0$r.squared
```

#### 4. 对回归方程做显著性检验

```{r}
# $运算符仅能提取F检验值，而未找到提取F检验P值的办法
# 其位于summary函数输出的最后一行
Sm0
```

#### 5. 对每一个回归系数做显著性检验

```{r}
Sm0$coefficients
```

#### 6. 如果有的回归系数没通过显著性检验，将其剔除，重新建立回归方程，再做方程的显著性检验和回归系数的显著性检验

```{r}
# 由上题结果P值，剔除X3
model1 = lm(Y ~ X1 + X2, data)
Sm1 = summary(model1)
Sm1
```

#### 7. 求出每一个回归系数的置信水平为95%的置信区间

```{r}
confint(model1)
```

#### 8. 求标准化回归方程

```{r}
model2 = lm(scale(Y) ~ scale(X1) + scale(X2), data)
model2
```

#### 9. 求当$x_{01}=75$，$x_{02}=42$，$x_{03}=3.1$时的$\hat{y}_0$，给定置信水平为95%，计算精确置信区间

```{r}
predict(model0, 
        newdata=data.frame(X1 = 75, X2 = 42, X3 = 3.1),
        se.fit=TRUE,
        interval="predict",
        level=.95)$fit
```
