---
title: 习题4.9
fig-height: 3
fig-width: 5
description: 违背基本假设的情况
---

> **下表是用电高峰每小时用电量$y$与每月总用电量$x$的数据。**

```{r}
library(haven)
data = read_sav("data/xt4.9.sav")
head(data)
```

#### 1. 用普通最小二乘法建立$y$与$x$的回归方程，并画出残差散点图

```{r}
model0 = lm(y ~ x, data)
model0
```

答：回归方程为：$\hat{y} = -0.8313 + 0.0037x$。

```{r}
library(ggplot2)
ggplot(model0, aes(x=x, y=.resid)) + 
    geom_point() + 
    geom_hline(yintercept = 0) + 
    labs(y="Residuals")
```

#### 2. 诊断该问题是否存在异方差性

```{r}
# 等级相关系数法（Spearman检验）
cor.test(data$x, 
         abs(resid(model0)), 
         alternative='two.sided',
         method="spearman", 
         conf.level=0.95)
```

答：$|e_i|$与$x_i$的等级相关系数=0.318，P值=0.021，存在异方差性。

#### 3. 如果存在异方差性，用幂指数型的权函数建立加权最小二乘回归方程

```{r}
# 编写寻找最优权函数
# 特定于幂指型权函数的一元回归
best_weight_1d = function(data, left=-2, right=2){
    the_seq = seq(left, right, 0.5)
    vec = rep(NA, length(the_seq))
    j = 1
    for (m in the_seq){
        model1 = lm(y ~ x,
                    weights=1/x^m,
                    data=data)
        vec[j] = logLik(model1) # logLik函数计算模型的对数似然值
        j = j + 1
    }
    best_local = which.max(vec)
    if(best_local != left & best_local != right){
        cat("幂指数最优取值为:", the_seq[best_local])
    }else if(best_local == left){
        cat("最优值在边界达到，请扩充范围（left）")
    }else{
        cat("最优值在边界达到，请扩充范围（right）")
    }
}
best_weight_1d(data)
```

```{r}
# 令m=1.5
model1 = lm(y ~ x, weights=1/x^1.5, data=data)
model1
```

答：加权最小二乘回归方程为：$\hat{y} = -0.683 + 0.00356x$。等级相关系数为-0.076，P值为0.591，异方差性已消除。因$R^2=0.659$，小于普通最小二乘的0.705，说明加权最小二乘的效果不好。

#### 4. 用方差稳定变换$y'=\sqrt{y}$消除异方差性

```{r}
data$y = sqrt(data$y)
model2 = lm(y ~ x, data)
model2
```

答：经过方差稳定性变换后的回归方程为：$\hat{y}^{'} = 0.5822 + 0.0009529x$。等级相关系数为0.160，P值为0.254，异方差性已消除。因$R^2=0.710$，优于普通最小二乘的效果。